### ISSUE TITLE
Single select control missing style with *ngif

### ISSUE THREAD

**Issue by alenabi** [creativetimofficial/light-bootstrap-dashboard-pro-angular#14]
Missing style
==============
`<select name="location" class="selectpicker"
                                                            data-title="Location"
                                                            data-style="btn-default btn-block"
                                                            data-menu-style="dropdown-blue" *ngIf="editMode">
                                                        <option value="id">Asia</option>
                                                        <option value="id">Europe</option>
                                                        <option value="id">America</option>
                                                    </select>`
================
Works fine (without *ngif)
================
`<select name="location" class="selectpicker"
                                                            data-title="Location"
                                                            data-style="btn-default btn-block"
                                                            data-menu-style="dropdown-blue">
                                                        <option value="id">Asia</option>
                                                        <option value="id">Europe</option>
                                                        <option value="id">America</option>
                                                    </select>`

**Comment by chelaruc** [comment]
Hi, @alenabi! 
Thank you for using our product! Can you tell me what editMode is doing?

Best,
Ciprian
