### ISSUE TITLE
How to add Brazilian language ('pt-br') ?

### ISSUE THREAD

**Issue by IomarSantos** [creativetimofficial/light-bootstrap-dashboard-pro-angular#20]
$('.datepicker').datetimepicker({
            format: 'MM/DD/YYYY',    //use this format if you want the 12hours timpiecker with AM/PM toggle
            locale: 'pt-br',
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
         });

**Comment by chelaruc** [comment]
Hi @IomarSantos,

Thank you for using our product. You need to add this `locale: 'br',` and in the scripts from `angular-cli.json` file add this: `"../node_modules/moment/locale/br.js",`

All the best,
Ciprian

**Comment by IomarSantos** [comment]
@chelaruc 
Thank
