### ISSUE TITLE
run swal from typscript?

### ISSUE THREAD

**Issue by coanpape** [creativetimofficial/light-bootstrap-dashboard-pro-angular#4]
Hi have you come up with a solution for running the swal dialogs directly from typescript?
npm annoyingly was allowing this when I had it transpiling in the background but since a restart I've been fixing issues, this is the one remaining.
Thank you

**Comment by coanpape** [comment]
By swal I mean Sweet Alerts, I am wondering if I need to refactor my code to perform the functions in .js.  A reply would be much appreciated

**Comment by alexandru-paduraru** [comment]
@coanpape thank you for using our product and sorry for the late response. Can you please give us more details about what is the issue? Are you looking to trigger the swal directly from typescript and not from the HTML, like how it is now? 

Something like the solution that we gave for the Bootstrap Table: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro-angular/issues/3 ?

Waiting for your reply so we can see how we can help :D

Best,
Alex

**Comment by coanpape** [comment]
Thanks, I needed to provide data to the dataTables in JSON and found that using the Angular functions were not working well with the dataTables, so went to their API and worked out a javascript solution.  Not ideal but I am prototyping for now so this suffices
