### ISSUE TITLE
CSS styling inconsistently applied to output?

### ISSUE THREAD

**Issue by coanpape** [creativetimofficial/light-bootstrap-dashboard-pro-angular#5]
Hi, I am working with the drop downs and multi-select examples from the extended forms page in an application prototype I am developing and am finding that the output is sometimes styled as desired (like your example) and sometimes not styled at all.  All it takes to change the behavior is to do a refresh, usually after a refresh the controls display as intended.  I am using Chrome.  
I have put the set of controls on a card as per your example and I have tried moving this card to various pages within my application and the behavior follows it.  I also tried putting the  card into the extended forms page of your dashboard app and the behavior is corrected.

I am working to isolate differences between the two applications, but wanted to check with you if this type of behavior has been observed by others and what had been done to correct it.
Thank you

**Comment by alexandru-paduraru** [comment]
@coanpape thank you for using our product. Can you please give us more details about the issue? I've tested and this is what we have on refresh, seems fine: https://vimeo.com/213883257

In the meantime, please make sure you call the method `$(".selectpicker").selectpicker();` which is activating the select picker and is located in `app/dashboard/forms/extendedforms/extendedforms.component.ts` line 26

Waiting for your answer so we can identify the issue and give you a solution.

Best,
Alex

**Comment by coanpape** [comment]
Hi Alex,
I had omitted the method $(".selectpicker").selectpicker(); 
The behavior without the initialization call is interesting, not what I would have expected of a component not being initialized.
I was really pounding my head on this one... 
Thank you!
