### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by coanpape** [creativetimofficial/light-bootstrap-dashboard-pro-angular#6]
Having deployed the angular quickstart project to a server (IIS), I have seen that there is a good bit of customization of the systemjs.config.js to generate a systemjs.config.server.js, as documented in Angular.io deployment tutorial as the simplest deployment possible: 
  https://angular.io/docs/ts/latest/guide/deployment.html 

I wanted to inquire if you have already done this for your deployments or if you have used an alternative method.

Thank you

**Comment by alexandru-paduraru** [comment]
@coanpape thank you for using our product and sorry for the late response. Here is the example of package.json that we are using to deploy on Heroku: https://github.com/creativetimofficial/light-bootstrap-dashboard-angular/blob/herokuLinks/package.json The file is from LBD Free, but it is the same that we have in LBD Pro. Please check it and let us know if that was helpful.

Best,
Alex
