### ISSUE TITLE
Import lodash ( Error ; or (  ) is expected in lodash.index.ts) or Underscore ( cannot find module underscore in component ) 

### ISSUE THREAD

**Issue by viksat7** [creativetimofficial/light-bootstrap-dashboard-pro-angular#8]
1. Lodash error : after npm start Error of either ; or ( ) expected in lodash/index.ts
installed lodash by npm install lodash and @types/lodash and applied map and packages in systemjs.config.js

2. Underscore error : after npm start Cannot find module underscore in component ( declared import * as _ from 'underscore' ) 
installed underscore by npm install underscore , added script reference in index.html and path in systemjs.config.js

**Comment by alexandru-paduraru** [comment]
@viksat7 can you please let us know when did you get this error? Do you have a npm-debug.log available? We didn't see this error before.

Best,
Alex
