### ISSUE TITLE
how to disable browser-sync ?

### ISSUE THREAD

**Issue by viksat7** [creativetimofficial/light-bootstrap-dashboard-pro-angular#9]
i could not find the browsersync.init function to set ghostmode options as false

**Comment by chelaruc** [comment]
Hi @viksat7,

Thank you for using our product! Tomorrow will be released v1.2.0 and this bug will be resolved.

All the best,
Ciprian

**Comment by manashreea** [comment]
Hello,

Where do I get browser-sync and how do i fixed it. I am using Light Bootstrap Dashboard PRO Angular 2 - V1.0.1

**Comment by viksat7** [comment]
@manashreea create a new file in project as bs-config.json as add following json

{
  "ghostMode": false
}

**Comment by manashreea** [comment]
Thanks for help, solution is working in development but the same is not working in production server. Can you recommend any solution for the same.
package.json using start script is "tsc && concurrently \"tsc -w\" \"lite-server -c my-bs-config.json\" "
On production command is -->  pm2 start "/usr/lib/node_modules/npm" --name "webapp" -- start
